#ifndef __MQTT_H__
#define __MQTT_H__

#include <esp_err.h>

#define ESP_MQTT_USERNAME           CONFIG_ESP_MQTT_USERNAME
#define ESP_MQTT_PASSWORD           CONFIG_ESP_MQTT_PASSWORD

#define ESP_MQTT_TOPIC_TEMPERATURE      CONFIG_ESP_MQTT_TOPIC_TEMPERATURE
#define ESP_MQTT_TOPIC_HUMIDITY         CONFIG_ESP_MQTT_TOPIC_HUMIDITY
#define ESP_MQTT_TOPIC_BATTERY_VOLTAGE  CONFIG_ESP_MQTT_TOPIC_BATTERY_VOLTAGE
#define ESP_MQTT_TOPIC_BATTERY_SOC      CONFIG_ESP_MQTT_TOPIC_BATTERY_SOC

esp_err_t mqtt5_init(void);

#endif // __MQTT_H__